#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON=calised
ARGS=

[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON

PID=$(get_pid $DAEMON)

case "$1" in
    start)
        stat_busy "Starting $DAEMON"
        if [ ! -z "$PID" ]; then
            stat_fail
            exit 1
        fi
        $DAEMON $ARGS &>/dev/null & sleep 1
        $DAEMON --check &>/dev/null
        if [ $? -eq 0 ]; then
            add_daemon $DAEMON
            stat_done
        else
            stat_fail
            exit 1
        fi
        ;;
    stop)
        stat_busy "Stopping $DAEMON"
        [ -n "$PID" ] && $DAEMON -k &>/dev/null
        if [ $? -eq 0 ]; then
            rm_daemon $DAEMON
            stat_done
        else
            stat_fail
            exit 1
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
esac
