#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON=calised
ARGS=

[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON

# stupid pidof's python behaviour... almost only way to get pid from name
PID="$(ps -C $DAEMON -o pid,cmd | grep "python" | awk '{print $1}')"

case "$1" in
    start)
        stat_busy "Starting $DAEMON"
        if [ ! -z "$PID" ]
        then
            stat_fail
            exit 1
        fi
        $DAEMON $ARGS &>/dev/null &
        if [ ! -z "$(ps -C $DAEMON -o pid,cmd | grep "python" | awk '{print $1}')" ]
        then
            add_daemon $DAEMON
            stat_done
        else
            stat_fail
            exit 1
        fi
        ;;
    stop)
        stat_busy "Stopping $DAEMON"
        [ -n "$PID" ] && $DAEMON -k &>/dev/null
        if [ $? -eq 0 ]
        then
            rm_daemon $DAEMON
            stat_done
        else
            stat_fail
            exit 1
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
esac
